<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="/assets/admin/vendors/popper/popper.min.js"></script>
<script src="/assets/admin/vendors/bootstrap/bootstrap.min.js"></script>
<script src="/assets/admin/vendors/anchorjs/anchor.min.js"></script>
<script src="/assets/admin/vendors/is/is.min.js"></script>
<script src="/assets/admin/vendors/choices/choices.min.js"></script>
<script src="/assets/admin/js/flatpickr.js"></script>
<script src="/assets/admin/vendors/dropzone/dropzone.min.js"></script>
<script src="/assets/admin/vendors/swiper/swiper-bundle.min.js"></script>
<script src="/assets/admin/vendors/rater-js/index.js"></script>
<script src="/assets/admin/vendors/chart/chart.min.js"></script>
<script src="/assets/admin/vendors/countup/countUp.umd.js"></script>
<script src="/assets/admin/vendors/echarts/echarts.min.js"></script>
<script src="/assets/admin/vendors/dayjs/dayjs.min.js"></script>
<script src="/assets/admin/vendors/fontawesome/all.min.js"></script>
<script src="/assets/admin/vendors/lodash/lodash.min.js"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="/assets/admin/vendors/list.js/list.min.js"></script>
<script src="/assets/admin/js/theme.js"></script>